version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
      DBT_PG_PASSWORD: ${DBT_PG_PASSWORD}
      SCRAPER_PG_PASSWORD: ${SCRAPER_PG_PASSWORD}
      GH_TOKEN: ${GH_TOKEN}
      SNS_TOPIC_ARN: ${SNS_TOPIC_ARN}
      SNS_ACCESS_KEY_ID: ${SNS_ACCESS_KEY_ID}
      SNS_SECRET_ACCESS_KEY: ${SNS_SECRET_ACCESS_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BACKUP_BUCKET: ${S3_BACKUP_BUCKET}
      MAGE_DATABASE_CONNECTION_URL: ${MAGE_DATABASE_CONNECTION_URL}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
